###############################################################################
# SubList.pl                                                                  #
###############################################################################
# YaBB: Yet another Bulletin Board                                            #
# Open-Source Community Software for Webmasters                               #
# Version:        YaBB 2.1                                                    #
# Released:       November 8, 2005                                            #
# Distributed by: http://www.yabbforum.com                                    #
# =========================================================================== #
# Copyright (c) 2000-2005 YaBB (www.yabbforum.com) - All Rights Reserved.     #
# Software by: The YaBB Development Team                                      #
#              with assistance from the YaBB community.                       #
# Sponsored by: Xnull Internet Media, Inc. - http://www.ximinc.com            #
#               Your source for web hosting, web design, and domains.         #
###############################################################################

$adminsublistplver = 'YaBB 2.1 $Revision: 1.2 $';

%director=(
'del_regentry',"RegistrationLog.pl&kill_registration",
'view_reglog',"RegistrationLog.pl&view_reglog",
'clean_reglog',"RegistrationLog.pl&clean_reglog",
'cleanerrorlog',"ErrorLog.pl&CleanErrorLog",
'convdelete',"Admin.pl&DeleteConverterFiles",
'errorlog',"ErrorLog.pl&ErrorLog",
'deleteerror',"ErrorLog.pl&DeleteError",
'delgroup',"MemberGroups.pl&deleteGroup",
'detailedversion',"Admin.pl&ver_detail",
'deletemultimembers',"Admin.pl&DeleteMultiMembers",
'deleteoldthreads',"Admin.pl&DeleteOldMessages",
'deletemail',"Admin.pl&MailList",
'do_clean_log',"Admin.pl&do_clean_log",
'editgroup',"MemberGroups.pl&editAddGroup",
'editgroup1',"MemberGroups.pl&editAddGroup",
'editAddGroup2',"MemberGroups.pl&editAddGroup2",
'editpaths',"AdminEdit.pl&EditPaths",
'editpaths2',"AdminEdit.pl&EditPaths2",
'flood_control',"Admin.pl&FloodControl",
'flood_control2',"Admin.pl&FloodControl2",
'deleteattachment',"Attachments.pl&DeleteAttachments",
'helpadmin',"EditHelpCentre.pl&MainAdmin",
'helpediting',"EditHelpCentre.pl&HelpEdit",
'helpediting2',"EditHelpCentre.pl&HelpEdit2",
'helpsettings2',"EditHelpCentre.pl&HelpSet2",
'helporder',"EditHelpCentre.pl&SetOrderFile",
'manageattachments',"Attachments.pl&Attachments",
'manageattachments2',"Attachments.pl&Attachments2",
'removeoldattachments',"Attachments.pl&RemoveOldAttachments",
'removebigattachments',"Attachments.pl&RemoveBigAttachments",
'modtemp',"ManageTemplates.pl&ModifyTemplate",
'modtemp2',"ManageTemplates.pl&ModifyTemplate2",
'modcss',"ManageTemplates.pl&ModifyCSS",
'modcss2',"ManageTemplates.pl&ModifyCSS2",
'modstyle',"ManageTemplates.pl&ModifyStyle",
'modstyle2',"ManageTemplates.pl&ModifyStyle2",
'modskin',"ManageTemplates.pl&ModifySkin",
'modskin2',"ManageTemplates.pl&ModifySkin2",
'modagreement',"AdminEdit.pl&ModifyAgreement",
'modagreement2',"AdminEdit.pl&ModifyAgreement2",
'modsettings',"AdminEdit.pl&ModifySettings",
'modsettings2',"AdminEdit.pl&ModifySettings2",
'modlist',"ModList.pl&ListMods",
'advsettings',"AdvSettings.pl&AdvSettings",
'advsettings2',"AdvSettings.pl&AdvSettings2",
'modmemgr',"MemberGroups.pl&EditMemberGroups",
'modmemgr2',"MemberGroups.pl&EditMemberGroups2",
'reordercats',"ManageCats.pl&ReorderCats",
'modifycatorder',"ManageCats.pl&ReorderCats",
'modifycat',"ManageCats.pl&ModifyCat",
'modifyboard',"ManageBoards.pl&ModifyBoard",
'managecats',"ManageBoards.pl&ManageBoards",
'mailinggrps',"MailMembers.pl&MailingMembers",
'mailing',"MailMembers.pl&Mailing",
'mailmultimembers',"Admin.pl&DeleteMultiMembers",
'mailing2',"MailMembers.pl&Mailing2",
'mailing3',"MailMembers.pl&Mailing3",
'membershiprecount',"Admin.pl&AdminMembershipRecount",
'manageboards',"ManageBoards.pl&ManageBoards",
'memlist',"ViewMembers.pl&MLB",
'memlistall',"ViewMembers.pl&ML",
'ml',"Admin.pl&ml",
'referer_control',"Admin.pl&Refcontrol",
'referer_control2',"Admin.pl&Refcontrol2",
'reorderboards',"ManageBoards.pl&ReorderBoards",
'reorderboards2',"ManageBoards.pl&ReorderBoards2",
'reordercats',"ManageCats.pl&ReorderCats",
'reordercats2',"ManageCats.pl&ReorderCats2",
'rebuildmemhist',"Admin.pl&RebuildMemHistory",
'rebuildmemlist',"Admin.pl&RebuildMemList",
'rebuildmesindex',"Admin.pl&RebuildMessageIndex",
'removeoldthreads',"RemoveOldTopics.pl&RemoveOldThreads",
'ipban',"Admin.pl&ipban",
'ipban2',"Admin.pl&ipban2",
'createcat',"ManageCats.pl&CreateCat",
'catscreen',"ManageCats.pl&DoCats",
'clean_log',"Admin.pl&clean_log",
'setcensor',"AdminEdit.pl&SetCensor",
'setcensor2',"AdminEdit.pl&SetCensor2",
'setreserve',"AdminEdit.pl&SetReserve",
'setreserve2',"AdminEdit.pl&SetReserve2",
'showclicks',"Admin.pl&ShowClickLog",
'stats',"Admin.pl&FullStats",
'smilies',"Smilies.pl&SmiliePanel",
'smilieput',"Smilies.pl&SmiliePut",
'smilieindex',"Smilies.pl&SmilieIndex",
'smiliemove',"Smilies.pl&SmilieMove",
'viewmembers',"ViewMembers.pl&MLByLetter",
'addboard',"ManageBoards.pl&AddBoards",
'addcat',"ManageCats.pl&AddCats",
'addcat2',"ManageCats.pl&AddCats2",
'addboard2',"ManageBoards.pl&AddBoards2",
'addmember',"Admin.pl&AddMember",
'addmember2',"Admin.pl&AddMember2",
'admin',"Admin.pl&Admin",
'assigned',"MemberGroups.pl&Assigned_Members",
'assigned2',"MemberGroups.pl&Assigned_Members2",
'boardrecount',"Admin.pl&AdminBoardRecount",
'boardscreen',"ManageBoards.pl&BoardScreen",
'editnews',"AdminEdit.pl&EditNews",
'editnews2',"AdminEdit.pl&EditNews2",
'addsmilies',"Smilies.pl&AddSmilies",
'gmodaccess',"AdminEdit.pl&GmodSettings",
'gmodsettings2',"AdminEdit.pl&GmodSettings2",
'setup_guardian',"GuardianAdmin.pl&setup_guardian",
'setup_guardian2',"GuardianAdmin.pl&setup_guardian2",
'updatenotify',"Admin.pl&UpdateNotify",
);

1;
